### ISSUE TITLE
unexpected `minimun-version` field on latest v2 release

### ISSUE THREAD

**Issue by francesco-furlan** [cpp-linter/cpp-linter-action#214]
It seems https://github.com/cpp-linter/cpp-linter-action/pull/210 broke the action

```
Error: cpp-linter/cpp-linter-action/v2/action.yml (Line: 221, Col: 5): Unexpected value 'minimum-version'
Error: cpp-linter/cpp-linter-action/v2/action.yml (Line: 225, Col: 5): Unexpected value 'minimum-version'
Error: cpp-linter/cpp-linter-action/v2/action.yml (Line: 229, Col: 5): Unexpected value 'minimum-version'
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. cpp-linter/cpp-linter-action/v2/action.yml (Line: 221, Col: 5): Unexpected value 'minimum-version',cpp-linter/cpp-linter-action/v2/action.yml (Line: 225, Col: 5): Unexpected value 'minimum-version',cpp-linter/cpp-linter-action/v2/action.yml (Line: 229, Col: 5): Unexpected value 'minimum-version'
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load cpp-linter/cpp-linter-action/v2/action.yml
```

**Comment by ClemensLinnhoff** [comment]
I am having the same issue.

**Comment by ClemensLinnhoff** [comment]
Thanks for the quickfix!
