### ISSUE TITLE
MkDocs deploy has been failing recently

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#69]
Failed jobs: https://github.com/cpp-linter/cpp-linter-action/actions/workflows/mkdocs-deploy.yml

```
Run git config user.name 'github-actions'
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/runner/work/cpp-linter-action/cpp-linter-action/site
WARNING  -  Both index.md and readme.md found. Skipping readme.md from /home/runner/work/cpp-linter-action/cpp-linter-action/docs
ERROR    -  Error reading page 'API Reference/cpp_linter.clang_format_xml.md': No module named 'mkdocstrings.handlers.python'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocstrings/handlers/base.py", line 563, in get_handler
    module = importlib.import_module(f"mkdocstrings_handlers.{name}")
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line [9](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:10)92, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line [10](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:11)50, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mkdocstrings_handlers'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line [11](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:12)30, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 215, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/markdown/blockparser.py", line [12](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:13)3, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocstrings/extension.py", line [17](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:18)5, in _process_block
    handler = self._handlers.get_handler(handler_name, handler_config)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mkdocstrings/handlers/base.py", line 565, in get_handler
    module = importlib.import_module(f"mkdocstrings.handlers.{name}")
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/importlib/__init__.py", line 1[26](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:27), in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 10[27](https://github.com/cpp-linter/cpp-linter-action/runs/6997858571?check_suite_focus=true#step:5:28), in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mkdocstrings.handlers.python'
Error: Process completed with exit code 1.
```

**Comment by 2bndy5** [comment]
funny I just noticed that. It seems the mkdocstring plugin recently updated in a breaking way. I didn't know it was a beta plugin.

I'm still looking into it. So far I've fixed the `ModuleNotFoundError`, but the mkdocstring behavior seems to have changed also (need to document the module name instead of the associated `__init__` module). Now I'm just fixing the cross-references in the dev docs.

**Comment by shenxianpeng** [comment]
> So far I've fixed the `ModuleNotFoundError`

Btw, do you find the reason why our last test (in this run https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/2527084295) did not show `ModuleNotFoundError`? We'd better prevent it from happening again

**Comment by 2bndy5** [comment]
Those CI workflows (on the test repo) aren't testing the docs build. The `ModuleNotFoundError` error was happening when running `mkdocs build` because the mkdocs plugin, mkdocstring, changed how their plugin is distributed via `pip install`; I think they're planning to add more than just python syntax support (hopefully).

**Comment by shenxianpeng** [comment]
Sorry, my bad. Actually, I want to ask the question about `FileNotFoundError` in the issue #67
